Podfile.lock, VideoApp/VideoApp.xcodeproj/xcshareddata/xcschemes/Video-TwilioUITests.xcscheme, VideoApp/VideoApp/Info.plist, VideoApp/VideoApp/Storyboards/Base.lproj/Main.storyboard
https://issues.corp.twilio.com/browse/AHOYAPPS-231
1. Enable landscape orientation for all screens. In the future I think we may want to only support portrait orientation on most screens but the current structure of our page stack does not allow for granular configuration.
1. Fixed the biggest sign in screen layout issues reported in original bug ticket by converting storyboard to use safe area layout guides to respect the notch. It's something we needed to do anyway.
1. Update SDK to 3.2.1.
1. Enable deep link UI tests because the main problem was caused by a web change that caused issues with `apple-app-site-association` file.
1. Basic video functions.
1. Made sure email sign in fields were not covered up by notch when user rotates left.
1. Made sure other screens looked correct with …
=> AHOYAPPS-301: Enable landscape orientation

VideoApp/VideoApp/Video/LocalMediaController+Internal.h, VideoApp/VideoApp/Video/LocalMediaController.m, VideoApp/VideoApp/Video/VideoAppCameraSource.m
https://issues.corp.twilio.com/browse/AHOYAPPS-314
1. Just unpublish video when app is in background and publish again when app returns to foreground.
1. Use video with 2 participants and make sure participant A sees participant B video change to muted when participant B sends app to background. And make sure participant A sees participant B video unmute when participant B returns app to foreground.
=> AHOYAPPS-314: Unpublish video in background

VideoApp/VideoApp.xcodeproj/project.pbxproj, VideoApp/VideoApp/Stores/AppSettings/CodableContainer.swift, VideoApp/VideoApp/Stores/AppSettings/JSONContainer.swift, VideoApp/VideoApp/Stores/AppSettings/Storage.swift
https://issues.corp.twilio.com/browse/AHOYAPPS-321
1. iOS 12 has a bug that causes JSONEncoder and JSONDecoder to fail with valid JSON. To avoid the problem wrap each setting in a container struct. A little unusual but least bad option I think. This way we can still use Codable objects to store settings. When we drop iOS 12 in the future we could consider reverting this change with or without a migration. The worst that should happen is app settings would be reset.
1. Tested settings on iOS 11, 12, and 13.
=> AHOYAPPS-321: Fix iOS 12 settings bug

README.md
https://issues.corp.twilio.com/browse/AHOYAPPS-342
Until the new Twilio CLI plugin is public if we want to test we must replace this instruction:
- Run `twilio plugins:install @twilio/labs/plugin-rtc`.
With these instructions:
- Clone https://github.com/twilio-labs/plugin-rtc.
- Checkout `development` branch.
- Run `npm install`.
- Run `twilio plugins:link <PATH_TO_PLUGIN_REPO>`.
=> Update readme for passcode sign in

README.md
I will add the badge back after I make changes to App Center deploy to prevent this problem.
=> Remove CircleCI badge from readme because it is red when it shouldn't be

README.md
A customer had a problem getting started and I think it was caused by skipping `twilio login`. After looking closer I realized that login really is separate from install and so it should be a separate step.
=> Add Twilio CLI login instructions

VideoApp/Video-TwilioUITests/Activities/AuthActivities.swift
Having issues with the UI test. So force the test to wait for the settings button to be available.
There is a separate ticket to run tests on real hardware which seems reliable.
=> Status check workaround

VideoApp/Video-TwilioUITests/Activities/AuthActivities.swift, VideoApp/Video-TwilioUITests/Plans/UI.xctestplan, VideoApp/Video-TwilioUITests/Tests/DeepLinkTests.swift, VideoApp/Video-TwilioUITests/Tests/RoomTests.swift
1. Removed sign out workaround I added yesterday because it didn't work on CI even though it seemed to locally.
1. Remove sign out from join room test that is used for status check.
1. Remove join room test from main UI test plan because it will cause issues with sign out removed.
=> Remove sign out from status check test

VideoApp/VideoApp.xcodeproj/project.pbxproj, VideoApp/VideoApp/Helpers/SwiftToObjc.swift, VideoApp/VideoApp/ViewControllers/Stats/StatsViewController.m
https://issues.corp.twilio.com/browse/AHOYAPPS-663
Notification name was duplicated maybe accidentally or to avoid bridging problems. A bug was created when the name was changed in one place and not the other. So remove the duplicate code.
=> AHOYAPPS-663: Remove duplicate code that caused stats bug

VideoApp/VideoApp/Views/VideoView/VideoView.swift, VideoApp/VideoApp/Views/VideoView/VideoView.xib
https://issues.corp.twilio.com/browse/AHOYAPPS-681
The entire VideoApp.VideoView was hidden until we received a video frame. So if a track was switched off and we didn't have a frame the track switch off UI was not visible. To fix this only hide TwilioVideo.VideoView when there are no frames. 
I wanted to be surgical with this fix but in the future I think I may:
1. Separate error UI from this view so that it is really only doing video stuff.
1. When this view is displayed as the main video view and the track switch off UI is visible it is going to darken more of the view than is ideal. This is because in this case `contentMode = .scaleAspectFit`. And so it's going to darken not only the video but the empty space that the video did not take up. However this should never really happen …
=> AHOYAPPS-681: Fix track switch off UI bug

VideoApp/VideoApp/Stores/AppSettings/AppSettingsStore.swift, VideoApp/VideoApp/Stores/AppSettings/VideoCodec.swift, VideoApp/VideoApp/Video/Room/ConnectOptionsFactory.swift, VideoApp/VideoApp/Video/Tracks/Camera/CameraConfigFactory.swift
https://issues.corp.twilio.com/browse/AHOYAPPS-670
1. Used best practices outlined in ticket.
1. Added `VP8 Simulcast VGA` option to video codec setting.
1. Because I renamed `vp8Simulcast` to `vp8SimulcastHD` the video codec setting may be reset to default value when the software is installed which is actually a good thing.
=> Use documented best practices for codec settings

VideoApp/VideoApp/ViewControllers/Room/RoomViewController.swift
Simple retain cycle that caused us to leak RoomViewController which then caused a lot of things to be leaked.
This does not seem to fix the camera problem when app returns to foreground.
=> Fix retain cycle

VideoApp/VideoApp/Video/Participants/LocalParticipant.swift
This is to work around an SDK bug.
=> Disable instead of unpublish when video source is interrupted

Podfile, Podfile.lock, VideoApp/VideoApp.xcodeproj/project.pbxproj, VideoApp/VideoApp/Helpers/Notifications.swift, VideoApp/VideoApp/Stores/MainParticipant/MainParticipantStore.swift, VideoApp/VideoApp/Stores/Participants/ParticipantsStore.swift, VideoApp/VideoApp/Video/Participants/LocalParticipant.swift, VideoApp/VideoApp/Video/Participants/Participant.swift, VideoApp/VideoApp/Video/Participants/ParticipantDelegate.swift, VideoApp/VideoApp/Video/Participants/RemoteParticipant.swift, VideoApp/VideoApp/Video/Room/Room.swift, VideoApp/VideoApp/Video/Room/RoomFactory.swift, VideoApp/VideoApp/ViewControllers/Lobby/LobbyViewController.swift, VideoApp/VideoApp/ViewControllers/Room/RoomViewModel.swift
https://issues.corp.twilio.com/browse/AHOYAPPS-708
Pinning a participant can modify multiple participants. When a participant is modified we immediately broadcast the update. And so what was happening was participant A would get updated (causing track priority changes) and then participant B would get updated (causing more track priority changes). The end result was correct but we were updating priorities more than necessary which is confusing and inefficient.
Dominant speaker can also cause updates to multiple participants but probably was not a problem because we let the server manage priority for that. However it is a concern because it is a fragile interface.
We need to batch participant updates together so that we only change track priorities once, after all participant updates are …
=> AHOYAPPS-708: Prevent unnecessary video track priority updates

VideoApp/VideoApp/Video/Participants/LocalParticipant.swift
https://issues.corp.twilio.com/browse/AHOYAPPS-727
Views that display camera video were not immediately updated for source interruption events. So on the room screen it took a couple seconds for the camera video to resume after the app returned to the foreground. Much more responsive now with the fix.
=> AHOYAPPS-727: Fix slow camera resume

VideoApp/VideoApp/Video/Participants/LocalParticipant.swift
We decided disable is preferred in this situation so the comment doesn't really apply anymore.
=> Remove old comment

Podfile, Podfile.lock, VideoApp/Video-InternalTests/Mocks/MockAppSettingsStore.swift, VideoApp/Video-InternalUITests/Activities/DeepLinkActivities.swift, VideoApp/VideoApp/Stores/AppSettings/AppSettingsStore.swift, VideoApp/VideoApp/Video/Room/ConnectOptionsFactory.swift, VideoApp/VideoApp/ViewControllers/Settings/Advanced/AdvancedSettingsViewModel.swift
https://issues.corp.twilio.com/browse/AHOYAPPS-790
Just added a settings switch to toggle insights on and off. Default is set to on. This is one of the RTCRoomsDemo tickets.
=> AHOYAPPS-790: Add insights setting

fastlane/Fastfile
https://issues.corp.twilio.com/browse/AHOYAPPS-833
Change tag format from `builds/iosbeta/61` to `v0.61`.
I tested locally.
=> AHOYAPPS-833: Change tag format

README.md, VideoApp/Video-InternalTests/Specs/CommunityAuthStoreSpec.swift, VideoApp/Video-InternalTests/Specs/CommunityTwilioAccessTokenStoreSpec.swift, VideoApp/Video-InternalTests/Specs/PasscodeComponentsSpec.swift, VideoApp/VideoApp/API/Requests/CommunityCreateTwilioAccessTokenRequest.swift, VideoApp/VideoApp/Stores/Auth/CommunityAuthStore.swift, VideoApp/VideoApp/Stores/Auth/PasscodeComponents.swift
https://issues.corp.twilio.com/browse/AHOYAPPS-805
1. Add support for longer passcode format. The old format only used 4 digits to generate the URL which was not unique enough and some customers were running into conflicts. The only difference from an end user perspective is the passcode is now 14 digits instead of 10.
1. This is still backwards compatible with the shorter passcode format.
1. Using the latest [token server](https://github.com/twilio/twilio-video-app-ios#deploy-twilio-access-token-server) with old iOS software will produce an error when the user enters the passcode. The solution is to update iOS software to include changes in this PR.
=> AHOYAPPS-805: Longer passcode format

Podfile.lock
The Crashlytics and Fabric changes should have no impact. CocoaPods is just warning us that we should replace with `FirebaseCrashlytics` pod.
=> Update SDK to 3.7.1

Podfile.lock, README.md, VideoApp/Video-InternalTests/Specs/RemoteConfigStoreSpec.swift, VideoApp/VideoApp/API/Responses/CommunityCreateTwilioAccessTokenResponse.swift, VideoApp/VideoApp/Stores/RemoteConfig/RemoteConfigStore.swift, VideoApp/VideoApp/Video/Tracks/Camera/CameraConfigFactory.swift, VideoApp/VideoApp/Video/Tracks/Camera/CameraSourceFactory.swift
This PR contains support for the Programmable Video Go room type. The Go room type provides a similar peer-to-peer video app experience except for a smaller limit of two participants. If more than two participants join a room with this room type, then the video app will present an error. To learn more about Go, please visit [the Twilio blog](https://www.twilio.com/blog/announcing-twilio-video-webrtc-go).
=> Implement Go Room Type Support

VideoApp/VideoApp/Stores/Chat/ChatStore.swift, VideoApp/VideoApp/Storyboards/Base.lproj/Main.storyboard, VideoApp/VideoApp/ViewControllers/Chat/ChatViewController.swift
https://issues.corp.twilio.com/browse/VIDEO-3721
1. Add send message to `ChatStore` and compose button to placeholder UI.
2. FYI the sent message will be added to the message list in the next ticket that handles incoming messages from the SDK. Should be speedy since the chat SDK uses sockets.
1. Tested success by taping chat button > compose > enter message > send > done > disconnect from video room > reconnect to the same video room > tap chat > verify sent message is output in log. We have to go back out to the lobby to force chat messages to be reloaded because we aren't handling new messages yet.
2. Tested failure by taping chat button > compose > enter message > disable Wi-Fi in control center > send > wait 90 seconds for the chat SDK to report error > verify send error is output in …
=> VIDEO-3721: Send message

VideoApp/VideoApp.xcodeproj/project.pbxproj, VideoApp/VideoApp/Stores/Chat/ChatFileMessage.swift, VideoApp/VideoApp/Stores/Chat/ChatMessage.swift, VideoApp/VideoApp/Stores/Chat/ChatStore.swift, VideoApp/VideoApp/Stores/Chat/ChatStoreUpdate.swift, VideoApp/VideoApp/Stores/Chat/ChatTextMessage.swift, VideoApp/VideoApp/Stores/Chat/ChatUpdate.swift, VideoApp/VideoApp/ViewControllers/Chat/ChatViewController.swift, VideoApp/VideoApp/ViewControllers/Room/RoomViewController.swift, VideoApp/VideoApp/ViewControllers/Room/RoomViewModel.swift, VideoApp/VideoApp/ViewControllers/Room/RoomViewModelData.swift
https://issues.corp.twilio.com/browse/VIDEO-3724
1. Make `ChatStore` receive new messages.
2. Make `ChatStore` keep track if there are any unread messages.
3. Make `ChatStore` immediately mark new messages as read if the user is currently inside chat UI.
4. `ChatStore` can now handle all basic chat features. The only thing I am aware might require more changes to `ChatStore` is grouping of messages by author and date. This could be done in either the view model or `ChatStore`. Grouping will be one of the last tickets I work on.
1. Used log output to verify unread status is correct after chat is connected.
2. Used log output to verify unread status changes correctly on the room screen when user is not inside chat screen.
2. Used log output to verify unread status is always false on the …
=> VIDEO-3724: Receive new messages

CHANGELOG.md, README.md
After meeting with @spalmertwilio and @mmartikainen we agreed that it would be good to document important releases of Video App in the changelog.
In this PR I have added an entry for v0.81 which was the tagged version where we added support for Video Content Preferences and Client Track Switch Off Control. Customers who referenced the code might want to return for pointers on how to update their own apps to best take advantage of the 4.5.0 SDK release.
=> VIDEO-6809: Add a changelog entry for the 4.5.0 support release.

CHANGELOG.md, Podfile.lock
Enhancements
- Added support for `Audio Only` rooms.
- Improved reconnection time after network connectivity disruptions.
- This release is built with Xcode 12.5.1
API Changes
- Two new error codes `TVIErrorRoomAudioOnlyFlagNotSupportedError` (53124) and `TVIErrorRoomTrackKindNotSupportedError` (53125) are added to support `Audio Only` rooms. 
Known Issues
- Audio playback fails when running a simulator on a Mac Mini. [#182](https://github.com/twilio/twilio-video-ios/issues/182)
- Carthage is not currently a supported distribution mechanism for Twilio Video. Carthage does not currently work with `.xcframeworks` as documented [here](https://github.com/Carthage/Carthage/issues/2890). Once Carthage supports binary `.xcframeworks`, Carthage distribution will be re-added.
- Unpublishing and …
=> VIDEO-XXXX upgrade to 4.6.2

CHANGELOG.md, Podfile.lock
4.6.3 (December 10, 2021)
API Changes
- New error code `TVIErrorParticipantSessionLengthExceededError` (53216) is added to support configurable participant session limit.
Bug Fixes
- Fixed a bug where media could incorrectly be detected as not flowing after the network connectivity changes. [VIDEO-7685]
Known Issues
- Audio playback fails when running a simulator on a Mac Mini. [#182](https://github.com/twilio/twilio-video-ios/issues/182)
- Carthage is not currently a supported distribution mechanism for Twilio Video. Carthage does not currently work with `.xcframeworks` as documented [here](https://github.com/Carthage/Carthage/issues/2890). Once Carthage supports binary `.xcframeworks`, Carthage distribution will be re-added.
- Unpublishing and republishing a `LocalAudioTrack` or …
=> VIDEO-XXXX update dependency to 4.6.3

VideoApp/VideoApp.xcodeproj/project.pbxproj, VideoApp/VideoApp/Assets.xcassets/AccentColor.colorset/Contents.json, VideoApp/VideoApp/NewCode/Screens/Home/HomeView.swift, VideoApp/VideoApp/NewCode/Screens/MediaSetup/MediaSetupView.swift, VideoApp/VideoApp/NewCode/Screens/MediaSetup/MediaSetupViewModel.swift, VideoApp/VideoApp/NewCode/Screens/Room/RoomView.swift, VideoApp/VideoApp/NewCode/Screens/Room/RoomViewDependencyWrapper.swift, VideoApp/VideoApp/NewCode/Screens/Room/RoomViewModel.swift, VideoApp/VideoApp/NewCode/Views/Participant/ParticipantView.swift, VideoApp/VideoApp/NewCode/Views/Participant/ParticipantViewModel.swift, VideoApp/VideoApp/NewCode/Views/RoomToolbar/CameraToggleButton.swift, VideoApp/VideoApp/NewCode/Views/RoomToolbar/MicToggleButton.swift
1. Add Media setup screen before the user connects to the room.
2. Add black bars to local participant camera video so it isn't cropped. Users need to know exactly what the camera is capturing. This applies to the media setup screen and the video layouts that display the local participant. 
3. There were some minor UI adjustments to things like copy to be more consistent with the web app.
Will handle landscape orientation for this screen separately. Have higher priorities right now.
https://user-images.githubusercontent.com/1930363/158904126-fe113c4d-5cc2-43a7-819c-0df643094b53.mov
=> Add new media setup screen

VideoApp/VideoApp/SwiftUI/Screens/MediaSetup/MediaSetupViewModel.swift, VideoApp/VideoApp/SwiftUI/Screens/Room/RoomView.swift, VideoApp/VideoApp/SwiftUI/Views/Participant/ParticipantView.swift, VideoApp/VideoApp/SwiftUI/Views/Participant/ParticipantViewModel.swift
1. Reduce video flicker when track is shown or getting switched back on. There was both a blue (from the view that is shown when camera is off) and black flash so the flicker was particularly bad. I got rid of the black flash. Might be able to improve the blue flash later.
2. Display `Bob (You)` instead of just `You`. This is more consistent with the web app.
3. A couple copy changes.
=> Small improvements for testing feedback

.circleci/config.yml, CHANGELOG.md, ForTwilions.md, VideoApp/Video-CommunityTests/Info.plist, VideoApp/Video-InternalTests/Info.plist, VideoApp/Video-InternalTests/Specs/AppInfoStoreSpec.swift, VideoApp/Video-InternalTests/Stubs/StubAppInfo.swift, VideoApp/Video-InternalUITests/Info.plist, VideoApp/VideoApp/Info.plist, VideoApp/VideoApp/Stores/AppInfo/AppInfo.swift, VideoApp/VideoApp/Stores/AppInfo/AppInfoStore.swift, VideoApp/VideoApp/UIKit/Settings/General/GeneralSettingsViewModel.swift, fastlane/Fastfile
1. CI will build and distribute app when GitHub release is created. See `ForTwilions.md` for details.
2. Use semantic versioning for app version. Previously only the build number was incremented and we were displaying the build number as a version in some places.
=> Improve release process

VideoApp/VideoApp/SwiftUI/Screens/Home/HomeView.swift
Added navigationViewStyle modifier on HomeView's NavigationView to prevent it from being hidden away in portrait mode on iPadOS.
=> Use StackNavigationViewStyle to render HomeView correctly on iPadOS

VideoApp/VideoApp/Video.entitlements
Added entitlements for PiP iOS 15. You need to upgrade the provisioning profile with this entitlement for `Video-app-internal`.
=> VIDEO-11812 - Added entitlements for PiP iOS 15

CHANGELOG.md, VideoApp/VideoApp.xcodeproj/project.pbxproj, VideoApp/VideoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
* Programmable Video iOS SDK 5.8.2 [[XCFramework]](https://github.com/twilio/twilio-video-ios/releases/download/5.8.2/TwilioVideo.xcframework.zip) (checksum: XCFRAMEWORK_CHECKSUM).
Enhancements
- The Privacy Manifest is updated since the SDK does not collect API usage or call quality data for tracking purposes according to [Apple's documentation](https://developer.apple.com/app-store/user-privacy-and-data-use/).
Known Issues
- Audio playback fails in some cases when running a simulator on a Mac Mini. [#182](https://github.com/twilio/twilio-video-ios/issues/182)
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. [#34](https://github.com/twilio/twilio-video-ios/issues/34)
- H.264 video might become corrupted after a network handoff. …
=> Update Video iOS SDK to 5.8.2
