Podfile.lock
README.md
VideoApp/Video-TwilioTests/Specs/AuthErrorSpec.swift
VideoApp/Video-TwilioTests/Specs/CommunityAuthStoreSpec.swift
VideoApp/VideoApp/API/Passcode/Core/API.swift
VideoApp/VideoApp/API/Passcode/Core/APIError.swift
VideoApp/VideoApp/API/Passcode/Core/APIErrorResponse.swift
VideoApp/VideoApp/Stores/Auth/Core/AuthError.swift
VideoApp/VideoApp/ViewControllers/SignIn/AuthFlow.swift

1. Update readme for minor changes to plugin command syntax.
1. Handle new shape of error response.

Update readme and handle new error response

---

README.md

https://issues.corp.twilio.com/browse/AHOYAPPS-435
Small changes to make readmes more consistent.

AHOYAPPS-435: Readme consistency

---

VideoApp/VideoApp/Video/Participants/LocalParticipant.swift

https://issues.corp.twilio.com/browse/AHOYAPPS-697

AHOYAPPS-697: Fix source interruption priority

---

README.md

Just add the feature bullet to readme like web has.

Add bandwidth profile feature bullet to readme

---

VideoApp/Video-InternalTests/Mocks/MockRemoteConfigStore.swift
VideoApp/Video-InternalTests/Specs/CommunityAuthStoreSpec.swift
VideoApp/Video-InternalTests/Specs/CommunityTwilioAccessTokenStoreSpec.swift
VideoApp/Video-InternalTests/Specs/RemoteConfigStoreSpec.swift
VideoApp/Video-InternalTests/Stubs/StubCommunityCreateTwilioAccessTokenResponse.swift
VideoApp/VideoApp.xcodeproj/project.pbxproj
VideoApp/VideoApp/Stores/Auth/AuthStoreFactory.swift
VideoApp/VideoApp/Stores/Auth/CommunityAuthStore.swift
VideoApp/VideoApp/Stores/RemoteConfig/RemoteConfigStore.swift
VideoApp/VideoApp/Stores/RemoteConfig/RemoteConfigStoreFactory.swift
VideoApp/VideoApp/Stores/TwilioAccessToken/CommunityTwilioAccessTokenStore.swift
VideoApp/VideoApp/Stores/TwilioAccessToken/TwilioAccessTokenStoreFactory.swift
VideoApp/VideoApp/Video/Tracks/Camera/CameraConfigFactory.swift

https://issues.corp.twilio.com/browse/AHOYAPPS-849
Use 720p capture when the room type is P2P.

AHOYAPPS-849: Use 720p capture for P2P

---

README.md

Added a section in the readme to explain how the different room types affect the app's behavior.

AHOYAPPS-871: Document video app room type behavior

---

Podfile.lock

Update video SDK to 4.3

---

VideoApp/VideoApp/Stores/Auth/InternalAuthStore.swift

Just updating stage and dev URLs for the internal build variant.

Update stage and dev URLs

---

VideoApp/Video-CommunityTests/Info.plist
VideoApp/Video-InternalTests/Info.plist
VideoApp/Video-InternalUITests/Info.plist
VideoApp/VideoApp.xcodeproj/project.pbxproj
VideoApp/VideoApp/Info.plist

Increment build number for feature branch release

---

README.md
VideoApp/VideoApp/SwiftUI/Screens/MediaSetup/MediaSetupView.swift

1. Added SwiftUI info to readme.
2. Minor layout adjustment to 1 view.

Add SwiftUI to readme

---

CHANGELOG.md
VideoApp/VideoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

VIDEO-XXXX update to 5.2.0

---

CHANGELOG.md
VideoApp/VideoApp.xcodeproj/project.pbxproj

VIDEO-11611 update to 5.2.1

---

.circleci/config.yml
CHANGELOG.md
VideoApp/VideoApp.xcodeproj/project.pbxproj
VideoApp/VideoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- Updated circle CI Image.
- Updated Video SDK version.
- Updated Changelog.

VBLOCKS-XXXX Fix build

---

README.md

Updated the EOL banner with the new date: Dec 5, 2026, and linked to the updated Help Center article 

Updated the EOL banner with the new date

---

README.md

VBLOCKS-3616 - Removed EOL banner

---

README.md

Removing legacy Room types

---

.circleci/config.yml
CHANGELOG.md

VBLOCKS-3970 Fix deploy builds and update fastlane 

---

CHANGELOG.md
VideoApp/VideoApp/Info.plist

VBLOCKS-3970 update version number

---

.circleci/config.yml
fastlane/Fastfile
fastlane/Pluginfile

VBLOCKS-3553 Add firebase app dist support

---

Gemfile.lock

VBLOCKS-3553 firebase app dist added to gemfile

---

.circleci/config.yml
CHANGELOG.md
VideoApp/VideoApp.xcodeproj/project.pbxproj
VideoApp/VideoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
VideoApp/VideoApp/Info.plist
fastlane/Fastfile

ahoy app update with Video iOS SDK 5.9.0

VBLOCKS-4057 ahoy app update with 5.9.0

---

.circleci/config.yml
fastlane/Fastfile

VBLOCKS-XXXX Fix service json key file
